server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:quickhrms_test}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:your-password-here}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true

  sendgrid:
    api-key: ${SENDGRID_API_KEY:your-sendgrid-api-key-here}

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources.add-mappings: false

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

# File Server Configuration
file:
  storage-location: C:\Users\Administrator\Documents\File-Server-Test
