server:
 port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:quickhrms}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:your-password-here}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sendgrid:
    api-key: ${SENDGRID_API_KEY:your-sendgrid-api-key-here}

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources.add-mappings: false

application:
 security:
   jwt:
     secret-key: ${JWT_SECRET_KEY:your-jwt-secret-key-here}
     expiration: 86400000 # a day
     refresh-token:
       expiration: 604800000 # 7 days

# File Server Configuration
file:
  storage-location: C:\
