server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:quickhrms}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

  sendgrid:
    api-key: ${SENDGRID_API_KEY:}

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources.add-mappings: false

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

# File Server Configuration
file:
  storage-location: ${FILE_STORAGE_LOCATION:/app/files}

logging:
  level:
    root: INFO
    com.application: INFO
    org.springframework: WARN
    org.hibernate: WARN

